run_benchmarks: true
evaluate_benchmarks: true
dataset: "stardist_artificial_segmentation_dataset"
logging:
  file: null
  level: DEBUG

benchmarks:
  enabled:
    - stardist_artificial_segmentation
  parameters:
    stardist_artificial_segmentation:
      warmup_iterations: 0
      num_iterations: 1
      precisions:
        - "float32"
        # - "float64"
      cpu_resolutions:
        - [128, 128]
        - [256, 256]
        - [512, 512]
        - [1024, 1024]
        - [2048, 2048]
        # - [4096, 4096]
        # - [8192, 8192]
        # - [16384, 16384]
        # - [32768, 32768]
      gpu_resolutions:
        - [128, 128]
        - [256, 256]
        - [512, 512]
        - [1024, 1024]
        - [2048, 2048]
        # - [4096, 4096]
        # - [8192, 8192]
        # - [16384, 16384]
        # - [32768, 32768]
      devices:
        auto_detect: true
        exclude_patterns: []
        include_cpu: true
        include_gpu: true
      evaluation:
        included_results: None # defaults to latest per flavour
