run_benchmarks: true
evaluate_benchmarks: true
dataset: "test_dataset"
logging:
  file: null
  level: DEBUG

benchmarks:
  enabled:
    - test_benchmark
  parameters:
    test_benchmark:
      warmup_iterations: 2
      num_iterations: 5
      precisions:
        - "float32"
        - "float64"
      cpu_resolutions:
        - [512, 512]
      gpu_resolutions:
        - [512, 512]
      devices:
        auto_detect: true
        exclude_patterns: []
        include_cpu: true
        include_gpu: true
      evaluation:
        included_results: None # defaults to latest per flavour
    # next benchmark:
